apiVersion: v1
kind: Service
metadata:
  name: <desired-service-name>
  namespace: <expected-namespace>
spec:
  ports:
  - port: 80
    targetPort: <application-port>
    protocol: TCP
  selector:
    app: <application-name>